name: nlp
dependencies:
# - python=3.7
- numpy
- pandas=1.0.1
# - pytorch=1.3.1
# - torchvision
# - cudatoolkit=10.1 #For GPU training only
- gensim=3.8.1
- pip:
  # - azureml-defaults for aml deployment
  - azureml-sdk>=1.1.5
  - azureml-dataprep[pandas,fuse]>=1.3.5
  - mlflow>=1.6.0
  - azureml-mlflow>=1.1.5
  - azure-ai-textanalytics
  - azure-cosmos
  - azure-storage-blob==2.1.0
  - spacy==2.2.1
  - transformers==2.4.1
  - farm==0.4.1
  - flair==0.4.5
  - selenium==3.141.0
  - bs4
  - tqdm
  - boto3
  - scipy>=1.3.2
  - sklearn
  - seqeval
  - dotmap==1.3.0
  - pyyml
  ##DEMO ENV
  - streamlit==0.56
  ##DEV ONLY
  - pylint
  - pytest

#python -m ipykernel install --user --name nlp --display-name "Python (nlp)"