name: nlp
dependencies:
- python=3.7
- pytorch=1.3.1
- torchvision
- cudatoolkit=10.1 #For GPU training only
- gensim=3.8.1
- pip:
  # - azureml-defaults for aml deployment
  - azureml-sdk>=1.1.5
  - azureml-dataprep[pandas,fuse]>=1.3.5
  - mlflow>=1.6.0
  - azureml-mlflow>=1.1.5
  - azure-ai-textanalytics
  # - imblearn
  - spacy==2.2.1
  - transformers==2.4.1
  - farm==0.4.1
#   - 'git+https://github.com/deepset-ai/FARM.git'
  - flair==0.4.5
#   - git+https://github.com/zalandoresearch/flair.git
  - azure-storage-blob
  - selenium==3.141.0
  - bs4
  ##DEMO ENV
  - streamlit==0.56
#   - langdetect
#   - lightgbm
#   - pandas_ml
- numpy
- pandas=1.0.1
# - scikit-learn
# - nltk
# - nb_conda
# - matplotlib
# - seaborn

#python -m ipykernel install --user --name nlp --display-name "Python (nlp)"